In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

df = pd.read_csv("C:/Users/skabe/OneDrive/Documents/Rudder_Works/SCHOOL/MUT[I.T]/Technical Programming II/2024/TEST 2/bky6-3za5.csv")

# Understanding the dataset

# Display the first few rows of the dataset
print("First few rows of the dataset:")
print(df.head())

# Display the size of the dataset
print("\nSize of the dataset:")
print(df.shape)

# Display the data types of each column
print("\nData types of each column:")
print(df.dtypes)

# Display the columns of the dataset
print("\nColumns in the dataset:")
print(df.columns)

# Display summary statistics
print("\nSummary statistics:")
print(df.describe())

# Data slicing and indexing
print("\nData slicing and indexing example:")
print(df.iloc[:5, :3])  # Display the first 5 rows and first 3 columns

# Identify missing data
print("\nMissing data in each column:")
print(df.isnull().sum())


# Numerical data - suitable for regression, clustering, etc.
print("\nstructure_count example:")
print(df['structure_count'].head())

# Categorical data - suitable for classification, one-hot encoding, etc.
print("\nage_of_is example:")
print(df['age_of_is'].head())

# Boolean data - suitable for binary classification
#print("\nBoolean data example:")
#print(df['boolean_column'].head())

# DateTime data - suitable for time series analysis
print("\navg_hhsize example:")
print(df['avg_hhsize'].head())

First few rows of the dataset:
    is_cluster  pocket_name                pocket_alias   ward_id  \
0       4 in 1       4 in 1  Wallacedene 14 / J Section  19100006
1  Acacia Road  Acacia Road      Acacia Park - Parktown  19100066
2    Amy Biehl    Amy Biehl                 School Site  19100034
3  Appel Boord  Appel Boord                         NaN  19100022
4       Area K       Area K                 Never Never  19100088

           ward_councillor  avg_hhsize  area_ha  density_dwellings  \
0      Simpiwe Nonkeyizana        3.72    2.952          50.813008
1          Melanie Arendse        4.51    0.070         114.285714
2         Fikiswa Nkunzana        2.89    1.711         301.578025
3          Johanna Martlow        4.14    0.088         159.090909
4  Patrick (Pat) Pietersen        4.17    2.661         249.154453

   structure_count      age_of_is  ... toilets_full_flush  toilets_chemical  \
0              150  15 - 20 years  ...               32.0               0.0
1                8  10 - 15 years  ...                3.0               2.0
2              516  15 - 20 years  ...               93.0               0.0
3               14   5 - 10 years  ...               10.0               0.0
4              663  10 - 15 years  ...              121.0               0.0

   toilets_portable  toilets_container  toilets_other  toilets_total  \
0               0.0                0.0            0.0           32.0
1               0.0                0.0            0.0            5.0
2               0.0                0.0            0.0           93.0
3               0.0                0.0            0.0           10.0
4               0.0                0.0            0.0          121.0

   ratio_toilets_dwellings  pocket_code  centroidx  centroidy
0                      1:5    NORFOU001  18.732603 -33.863384
1                      1:2    HILACA001  18.501024 -34.032822
2                      1:6    MITAMY001  18.587852 -34.002772
3                      1:1    TYGAPP001  18.609142 -33.926268
4                      1:5    MITARE001  18.598543 -34.008208

[5 rows x 22 columns]

Size of the dataset:
(434, 22)

Data types of each column:
is_cluster                  object
pocket_name                 object
pocket_alias                object
ward_id                      int64
ward_councillor             object
avg_hhsize                 float64
area_ha                    float64
density_dwellings          float64
structure_count              int64
age_of_is                   object
upgrade_category            object
temp_sanitation            float64
toilets_full_flush         float64
toilets_chemical           float64
toilets_portable           float64
toilets_container          float64
toilets_other              float64
toilets_total              float64
ratio_toilets_dwellings     object
pocket_code                 object
centroidx                  float64
centroidy                  float64
dtype: object

Columns in the dataset:
Index(['is_cluster', 'pocket_name', 'pocket_alias', 'ward_id',
       'ward_councillor', 'avg_hhsize', 'area_ha', 'density_dwellings',
       'structure_count', 'age_of_is', 'upgrade_category', 'temp_sanitation',
       'toilets_full_flush', 'toilets_chemical', 'toilets_portable',
       'toilets_container', 'toilets_other', 'toilets_total',
       'ratio_toilets_dwellings', 'pocket_code', 'centroidx', 'centroidy'],
      dtype='object')

Summary statistics:
            ward_id  avg_hhsize     area_ha  density_dwellings  \
count  4.340000e+02  434.000000  434.000000         434.000000
mean   1.910006e+07    3.337143    4.462938         183.057795
std    3.102414e+01    0.535691   32.968974         182.105873
min    1.910000e+07    2.190000    0.010000           0.000000
25%    1.910004e+07    2.892500    0.140000          90.022903
50%    1.910007e+07    3.230000    0.389000         174.685262
75%    1.910009e+07    3.710000    1.904000         254.274750
max    1.910011e+07    5.110000  669.406000        3007.299270

       structure_count  temp_sanitation  toilets_full_flush  toilets_chemical  \
count       434.000000       434.000000          434.000000        434.000000
mean        337.744240        31.369426           31.283410         11.582949
std         859.580015        43.844564           87.902084         48.968423
min           0.000000         0.000000            0.000000          0.000000
25%          21.000000         0.000000            0.000000          0.000000
50%          53.000000         0.000000            4.000000          0.000000
75%         289.500000        89.193297           16.000000          0.000000
max        7963.000000       100.000000         1095.000000        578.000000

       toilets_portable  toilets_container  toilets_other  toilets_total  \
count        434.000000         434.000000     434.000000     434.000000
mean          36.700461          11.698157       2.836406      94.101382
std          205.429506          73.071471      28.036655     314.532145
min            0.000000           0.000000       0.000000       0.000000
25%            0.000000           0.000000       0.000000       3.000000
50%            0.000000           0.000000       0.000000      10.000000
75%            0.000000           0.000000       0.000000      57.500000
max         3109.000000         883.000000     525.000000    4807.000000

        centroidx   centroidy
count  434.000000  434.000000
mean    18.603335  -33.987186
std      0.106208    0.099290
min     18.341108  -34.202636
25%     18.544694  -34.025843
50%     18.590699  -34.005508
75%     18.662143  -33.985590
max     18.910236  -33.538179

Data slicing and indexing example:
    is_cluster  pocket_name                pocket_alias
0       4 in 1       4 in 1  Wallacedene 14 / J Section
1  Acacia Road  Acacia Road      Acacia Park - Parktown
2    Amy Biehl    Amy Biehl                 School Site
3  Appel Boord  Appel Boord                         NaN
4       Area K       Area K                 Never Never

Missing data in each column:
is_cluster                   0
pocket_name                  0
pocket_alias               242
ward_id                      0
ward_councillor              0
avg_hhsize                   0
area_ha                      0
density_dwellings            0
structure_count              0
age_of_is                    0
upgrade_category             0
temp_sanitation              0
toilets_full_flush           0
toilets_chemical             0
toilets_portable             0
toilets_container            0
toilets_other                0
toilets_total                0
ratio_toilets_dwellings     91
pocket_code                  0
centroidx                    0
centroidy                    0
dtype: int64

structure_count example:
0    150
1      8
2    516
3     14
4    663
Name: structure_count, dtype: int64

age_of_is example:
0    15 - 20 years
1    10 - 15 years
2    15 - 20 years
3     5 - 10 years
4    10 - 15 years
Name: age_of_is, dtype: object

avg_hhsize example:
0    3.72
1    4.51
2    2.89
3    4.14
4    4.17
Name: avg_hhsize, dtype: float64